### ISSUE TITLE
In the Excalidraw plugin, display problems occur when dark mode is used

### ISSUE THREAD

**Issue by xiaowang27** [lorens-osman-dev/Glass-Robo#2]
Hello! I like the dark mode of this theme very much, but it will have some display problems at some time. I have attached the picture, I hope you can take time out of your busy schedule to have a look!
![Snipaste_2024-12-08_19-44-46](https://github.com/user-attachments/assets/a4f54ae2-3ace-43da-bb84-7757e9f73916)
![Snipaste_2024-12-08_19-44-57](https://github.com/user-attachments/assets/682af733-bce3-4702-ad93-d8a80dfd0ef7)

**Comment by lorens-osman-dev** [comment]
fixed.
enjoy!
